/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-light': 'var(--primary-light)',
        'primary-dark': 'var(--primary-dark)',
        'primary-subtle': 'var(--primary-subtle)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card-background)',
        border: 'var(--border-color)',
        success: 'var(--success)',
        'success-light': 'var(--success-light)',
        'success-dark': 'var(--success-dark)',
        'success-subtle': 'var(--success-subtle)',
        error: 'var(--error)',
        'error-light': 'var(--error-light)',
        'error-dark': 'var(--error-dark)',
        'error-subtle': 'var(--error-subtle)',
        warning: 'var(--warning)',
        'warning-light': 'var(--warning-light)',
        'warning-dark': 'var(--warning-dark)',
        'warning-subtle': 'var(--warning-subtle)',
        info: 'var(--info)',
        'info-light': 'var(--info-light)',
        'info-dark': 'var(--info-dark)',
        'info-subtle': 'var(--info-subtle)',
        muted: 'var(--muted)',
        'muted-light': 'var(--muted-light)',
        'muted-dark': 'var(--muted-dark)',
        'muted-subtle': 'var(--muted-subtle)',
        'syntax-added-bg': 'var(--syntax-added-bg)',
        'syntax-added-text': 'var(--syntax-added-text)',
        'syntax-added-border': 'var(--syntax-added-border)',
        'syntax-removed-bg': 'var(--syntax-removed-bg)',
        'syntax-removed-text': 'var(--syntax-removed-text)',
        'syntax-removed-border': 'var(--syntax-removed-border)',
        'syntax-neutral': 'var(--syntax-neutral)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: 'var(--radius-sm)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        'soft': '0 2px 8px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.1)',
        'medium': '0 4px 12px rgba(0, 0, 0, 0.15), 0 2px 4px rgba(0, 0, 0, 0.1)',
        'strong': '0 8px 24px rgba(0, 0, 0, 0.2), 0 4px 8px rgba(0, 0, 0, 0.15)',
        'glow': '0 0 20px var(--primary-subtle)',
        'glow-success': '0 0 20px var(--success-subtle)',
        'glow-error': '0 0 20px var(--error-subtle)',
        'card': '0 4px 12px rgba(0, 0, 0, 0.05), 0 2px 4px rgba(0, 0, 0, 0.03)',
        'card-hover': '0 8px 24px rgba(0, 0, 0, 0.1), 0 4px 8px rgba(0, 0, 0, 0.06)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-gentle': 'bounce 2s infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}